HAS_LIBZ=1
LIBNAME=gcop
SRCS=chrinfo.cpp \
     fieldformat.cpp \
     fieldtypes.cpp \
     gcords.cpp \
     tabfield.cpp \
     l_file.cpp \
     timer.cpp \
     tokenreader.cpp \
     script/cmd_base.cpp \
     script/cmdparam.cpp \
     script/command.cpp \
     script/objs_base.cpp \
     script/objs.cpp \
     script/objspace.cpp \
     script/scriptenv.cpp

#-------------------------------------------------------------------------------

include ../../makefile.mk

#-------------------------------------------------------------------------------

all: $(TARGETS)
